
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Jiaxi Gao  ## put your name
title: 'Master of Applied Science Student; Deep Learning Research Assistant'  ## your title
location: Vancouver, BC, Canada


## Social Profiles
facebook: https://www.facebook.com/jiaxi.gao.14  ## your facebook account url
twitter: https://twitter.com/JiaxiGao  ## your twitter account url
linkedin: https://www.linkedin.com/in/jiaxi-gao-93745710b/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
